build_from:
  aarch64: homeassistant/aarch64-base:3.19
  amd64: homeassistant/amd64-base:3.19
  armhf: homeassistant/armhf-base:3.19
  armv7: homeassistant/armv7-base:3.19
  i386: homeassistant/i386-base:3.19
args:
  BUILD_DATE: "2024-09-20-v9"
  BUILD_VERSION: "1.0.8"