build_from:
  aarch64: ghcr.io/home-assistant/base:3.18
  amd64: ghcr.io/home-assistant/base:3.18
  armhf: ghcr.io/home-assistant/base:3.18
  armv7: ghcr.io/home-assistant/base:3.18
  i386: ghcr.io/home-assistant/base:3.18
args:
  BUILD_DATE: "2024-09-20-v8"
  BUILD_VERSION: "1.0.7"