build_from:
  aarch64: ghcr.io/home-assistant/base-python:3.11-alpine3.18
  amd64: ghcr.io/home-assistant/base-python:3.11-alpine3.18
  armhf: ghcr.io/home-assistant/base-python:3.11-alpine3.18
  armv7: ghcr.io/home-assistant/base-python:3.11-alpine3.18
  i386: ghcr.io/home-assistant/base-python:3.11-alpine3.18
args: {}