build_from:
  aarch64: python:3.11-alpine
  amd64: python:3.11-alpine
  armhf: python:3.11-alpine
  armv7: python:3.11-alpine
  i386: python:3.11-alpine
args:
  BUILD_DATE: "2024-09-20-v6"
  BUILD_VERSION: "1.0.5"